"""Empty package marker for /tests/adversarial/.

This directory will hold:
  - phi_corpus.jsonl          (Phase 1, 150+ cases)
  - dosage_trick_tuning.jsonl (Phase 2, 30+ cases)
  - dosage_trick_heldout.jsonl (Phase 2, 10+ cases — generated by Claude Sonnet 5)
  - emergency_corpus.jsonl    (Phase 2, emergency cases)

Per spec §10.2, the held-out dosage-trick set must NEVER be used to tune
Layer 1 or Layer 2 — if a rule is edited specifically to pass a held-out
case, that case has been converted to a tuning case and must be replaced
with a fresh held-out case (documented in /docs/phase2_metrics.md).
"""
